CREATE TABLE IF NOT EXISTS purchase_orders
(
    id              INT UNSIGNED UNIQUE AUTO_INCREMENT         NOT NULL,
    po_number       VARCHAR(10)                                NOT NULL,
    vendor_id       INT UNSIGNED                               NOT NULL,
    buyer_id        INT UNSIGNED                               NOT NULL,
    status          TINYINT UNSIGNED DEFAULT 0                 NOT NULL,
    description     VARCHAR(500)                               NOT NULL,
    order_date      DATE                                       NOT NULL,
    ship_date       DATE             DEFAULT NULL,
    cancel_date     DATE             DEFAULT NULL,
    shipping_notes  TEXT             DEFAULT NULL,
    terms           VARCHAR(255)     DEFAULT ''                NOT NULL,
    ship_to_address VARCHAR(500)     DEFAULT ''                NOT NULL,
    fob_type        TINYINT UNSIGNED DEFAULT 0                 NOT NULL,
    fob_point       VARCHAR(255)     DEFAULT ''                NOT NULL,
    notes           TEXT             DEFAULT NULL,
    total_amount    DECIMAL(12, 2)   DEFAULT 0.00              NOT NULL,
    created_at      DATETIME         DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (po_number),
    INDEX (vendor_id),
    INDEX (buyer_id),
    FOREIGN KEY (vendor_id) REFERENCES vendors (id),
    FOREIGN KEY (buyer_id) REFERENCES users (id)
)
