CREATE TABLE IF NOT EXISTS vendors (
    id         INT UNSIGNED UNIQUE AUTO_INCREMENT NOT NULL,
    name       VARCHAR(255) NOT NULL,
    code       CHAR(3) NOT NULL,
    status     TINYINT UNSIGNED DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by INT UNSIGNED NOT NULL REFERENCES users(id),
    PRIMARY KEY (id),
    UNIQUE (code)
)
